# Generated by Django 3.2.4 on 2021-07-06 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialNetwork', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='token',
            field=models.CharField(default='7eeff10d-740d-4c3b-b422-65f5fbbfd6c2', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_custom_id',
            field=models.BigIntegerField(default=21281318, unique=True),
        ),
    ]
