# Generated by Django 3.2.4 on 2021-07-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialNetwork', '0002_auto_20210706_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='token',
            field=models.CharField(default='078c8bf6-ee65-413e-a34e-78dde6497124', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_custom_id',
            field=models.BigIntegerField(default=79655774, unique=True),
        ),
    ]
