# Generated by Django 3.2.4 on 2021-07-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialNetwork', '0003_auto_20210706_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='images/photo'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='user__username', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='token',
            field=models.CharField(default='54e9783a-b4cd-4d96-9bdf-82365903e8c5', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_custom_id',
            field=models.BigIntegerField(default=50163551, unique=True),
        ),
    ]
