# Generated by Django 3.2.4 on 2021-07-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialNetwork', '0004_auto_20210719_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ManyToManyField(to='SocialNetwork.Photo'),
        ),
    ]
