# Generated by Django 3.2.4 on 2021-07-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialNetwork', '0005_auto_20210707_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='token',
            field=models.CharField(default='0193197f-e2ad-43f2-a941-f852a1a6d64c', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_custom_id',
            field=models.BigIntegerField(default=23146598, unique=True),
        ),
    ]
