# Generated by Django 3.2.4 on 2021-07-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SocialNetwork', '0005_alter_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ManyToManyField(blank=True, related_name='photo', to='SocialNetwork.Photo'),
        ),
    ]
